version: '3'

volumes:
  gmv-data:

services:
  api-gmv:
    build: .
    container_name: api-gmv
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - database-gmv

  database-gmv:
    image: kartoza/postgis:11.0-2.5
    container_name: database-gmv
    volumes:
      - gmv-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 25432:5432
    restart: on-failure
    healthcheck:
      test: 'exit 0'
